version: "2.1"

services:
  server:
    build:
      context: server
    command: bash -c "python server/manage.py makemigrations && python server/manage.py migrate && python server/manage.py runserver 0.0.0.0:8000"
    container_name: server
    volumes:
      - .:/server
    ports:
      - "8000:8000"
  client:
    container_name: client
    build:
      context: client
    volumes:
      - .:/client
    ports:
      - "3000:3000"
